%cama de raya,
Longitud_tablero = 1370.000 #P1#
Anchura__tablero = 503.000 #P2#
Grosor___tablero = 24.000 #P3#
PARINI 1 #x# #1370#
PARINI 2 #y# #503#
PARINI 3 #z# #24#
CALCULO P1=1370;{X}
P2=503;{Y}
P3=24;{Z}
P11=40;{DESDE X}
P12=0;{DESDE Y}
P13=100+40;{HASTA X}
P14=100;{HASTA Y}
P15=6;{PROFUNDIDAD}
#
CICLO_USU medios\jesus\cama\rayas\raya
CALCULO P1=1370;{X}
P2=503;{Y}
P3=24;{Z}
P11=40+18;{DESDE X}
P12=0;{DESDE Y}
P13=100+40+18;{HASTA X}
P14=100;{HASTA Y}
P15=6;{PROFUNDIDAD}
#
CICLO_USU medios\jesus\cama\rayas\raya
CALCULO P1=1370;{x}
P2=503;{y}
P3=24;{z}
P11=260;{desde x}
P12=0;{desde y}
P13=260;{hasta x}
P14=100;{hasta y}
P15=6;{profundidad}
#
CICLO_USU medios\jesus\cama\rayas\raya
CALCULO P1=1370;{X}
P2=503;{Y}
P3=24;{Z}
P11=260+12;{DESDE X}
P12=0;{DESDE Y}
P13=260+12;{HASTA X}
P14=100;{HASTA Y}
P15=6;{PROFUNDIDAD}
#
CICLO_USU medios\jesus\cama\rayas\raya
